import {
  Product1,
  Product2,
  Product3,
  Product4,
  Product5,
  Product6,
  Product7,
  Product8,
  Product9
} from "../constants/Data";
const ProductDetails = [
  {
    category: "Dresses",
    img: Product1,
    name: "Jersey",
    size: ["XL", "M", "L"],
    body: "This jersey is made from a breathable, moisture-wicking polyester blend that keeps you cool and dry.",
    price: "400",
  },
  {
    category: "Shoes",
    img: Product2,
    name: "Shoes",
    size: ["38", "40", "42"],
    body: "This jersey is made from a breathable, moisture-wicking polyester blend that keeps you cool and dry.",
    price: "1000",
  },
  {
    category: "Balls",
    img: Product3,
    name: "VolleyBall",
    size: ["M", "L"],
    body: "This jersey is made from a breathable, moisture-wicking polyester blend that keeps you cool and dry.",
    price: "250",
  },
  {
    category: "Medal",
    img: Product4,
    name: "Gold Medal",
    size: ["20g", "30g"],
    body: "This jersey is made from a breathable, moisture-wicking polyester blend that keeps you cool and dry.",
    price: "60",
  },
  {
    category: "Medal",
    img: Product6,
    name: "bronze Medal",
    size: ["20g", "30g"],
    body: "This jersey is made from a breathable, moisture-wicking polyester blend that keeps you cool and dry.",
    price: "60",
  },
  {
    category: "Medal",
    img: Product5,
    name: "Silver Medal",
    size: ["20g", "30g"],
    body: "This jersey is made from a breathable, moisture-wicking polyester blend that keeps you cool and dry.",
    price: "60",
  },
  {
    category: "Bottle",
    img: Product7,
    name: "Glass Bottle",
    size: ["20g", "30g"],
    body: "This jersey is made from a breathable, moisture-wicking polyester blend that keeps you cool and dry.",
    price: "60",
  },
  {
    category: "Dresses",
    img: Product8,
    name: "Tracksuit",
    size: ["M", "L", "XL"],
    body: "This jersey is made from a breathable, moisture-wicking polyester blend that keeps you cool and dry.",
    price: "700",
  },
  {
    category: "Balls",
    img: Product9,
    name: "Netball",
    size: ["M", "L"],
    body: "This jersey is made from a breathable, moisture-wicking polyester blend that keeps you cool and dry.",
    price: "900",
  },
];

export default ProductDetails;